---
# tasks file for kvm_setup
- name: Install virt packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items: "{{ package_names  }}"

- name: Add user to libvirt group
  user:
    name: emilan
    groups: libvirt
    append: true

- name: Add user to kvm group
  user:
    name: emilan
    groups: kvm
    append: true

- name: Move root ssh key
  authorized_key:
    user: emilan
    state: present
    key: "{{ lookup('file', '/home/emilan/.ssh/root_kvm.pub') }}"

- name: Create images under home dir
  file:
    path: /home/emilan/images
    state: directory
    recurse: true
    owner: emilan
    group: kvm

- name: Find all vmlinuz-* files
  find:
    paths: /boot/
    patterns: "vmlinuz-*"
  register: files_to_change

- name: Change vmlinuz permissions because of a bug that is not fixed in ubuntu
  file:
    path: "{{ item.path }}"
    mode: a+r
  with_items: "{{ files_to_change.files }}"

- name: Copy qemu.conf template to server
  template:
    src: qemu.conf.j2
    dest: /etc/libvirt/qemu.conf

- name: Copy libvirtd.conf file to server
  copy:
    src: libvirtd.conf
    dest: /etc/libvirt/libvirtd.conf

- name: Start and enabled libvirtd
  service:
    name: libvirtd
    enabled: true
    state: started

- name: Copy netcfg tempalte to server
  template:
    src: 01-netcfg.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml

- name: Run netplan apply
  command: /usr/sbin/netplan apply

- name: Reboot after doing everything
  reboot:
