---
# tasks file for kvm_setup
- name: Install virt packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items: "{{ package_names  }}"

- name: Add user to libvirt group
  user:
    name: emilan
    groups: libvirt
    append: true

- name: Add user to kvm group
  user:
    name: emilan
    groups: kvm
    append: true

- name: Create images under home dir
  file:
    path: /home/emilan/images
    state: directory
    recurse: true
    owner: emilan
    group: kvm

- name: Copy libvirtd.conf file to server
  copy:
    src: libvirtd.conf
    dest: /etc/libvirt/libvirtd.conf

- name: Start and enabled libvirtd
  service:
    name: libvirtd
    enabled: true
    state: started

- name: Copy netcfg tempalte to server
  template:
    src: 01-netcfg.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml

- name: Run netplan apply
  command: /usr/sbin/netplan apply

- name: Reboot after doing everything
  reboot:
